<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

/**
 * The approved Seller Center copy, in both languages (design handoff 12).
 *
 * The panel's `translate()` writes a title-cased guess for any key it has never seen, which is why
 * an unseeded panel reads "Nav orders" and "Sla risk". Seeding the approved strings is the only way
 * the shipped wording is the wording that was signed off — and it keeps English and Arabic in step,
 * since a key added to one file and forgotten in the other is the usual way a bilingual product
 * drifts.
 *
 * Run with `php artisan db:seed --class=SellerCenterCopySeeder`. It only ever adds and corrects the
 * keys listed here; every other line in those files is left exactly as it was.
 */
class SellerCenterCopySeeder extends Seeder
{
    /** Arabic ships in the `sy` locale folder; `sa` carries the same strings. */
    private const ARABIC_LOCALES = ['sy', 'sa'];

    public function run(): void
    {
        $this->write('en', array_map(static fn (array $pair) => $pair[0], self::COPY));

        $arabic = array_map(static fn (array $pair) => $pair[1], self::COPY);
        foreach (self::ARABIC_LOCALES as $locale) {
            $this->write($locale, $arabic);
        }
    }

    /** @param array<string, string> $strings */
    private function write(string $locale, array $strings): void
    {
        $path = base_path('resources/lang/' . $locale . '/new-messages.php');

        if (!is_file($path)) {
            return;
        }

        $existing = include $path;
        if (!is_array($existing)) {
            return;
        }

        $merged = array_merge($existing, $strings);
        ksort($merged, SORT_NATURAL | SORT_FLAG_CASE);

        // var_export, not concatenation: a string carrying a quote or a backslash written into a
        // double-quoted PHP literal makes this file — which is included on every translate() call —
        // unparsable, and takes the whole site down with it.
        $contents = "<?php\n\nreturn [\n";
        foreach ($merged as $key => $value) {
            $contents .= "\t" . var_export((string) $key, true) . ' => ' . var_export((string) $value, true) . ",\n";
        }
        $contents .= "];\n";

        file_put_contents($path, $contents);

        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($path, true);
        }

        $this->command?->info($locale . ': ' . count($strings) . ' Seller Center strings written');
    }

    /**
     * key => [English, Arabic]. Sections follow handoff 12.
     *
     * @var array<string, array{0: string, 1: string}>
     */
    private const COPY = [
        // ── 1. navigation ────────────────────────────────────────────────
        'nav_home' => ['Home', 'الرئيسية'],
        'nav_seller_home' => ['Seller Home', 'لوحة البائع'],
        'nav_control_tower' => ['Control Tower', 'مركز التحكم'],
        'nav_action_center' => ['Action Center', 'مركز المهام'],
        'nav_orders' => ['Orders', 'الطلبات'],
        'nav_all_orders' => ['All orders', 'كل الطلبات'],
        'nav_ready_to_ship' => ['Ready to ship', 'جاهز للشحن'],
        'nav_shipped' => ['Shipped', 'تم الشحن'],
        'nav_delivered' => ['Delivered', 'تم التسليم'],
        'nav_cancelled' => ['Cancelled', 'ملغى'],
        'nav_returns' => ['Returns', 'المرتجعات'],
        'nav_refunds' => ['Refunds', 'المبالغ المستردة'],
        'nav_messages' => ['Messages', 'المحادثات'],
        'nav_catalog' => ['Catalog', 'الكتالوج'],
        'nav_products' => ['Products', 'المنتجات'],
        'nav_add_product' => ['Add product', 'إضافة منتج'],
        'nav_drafts' => ['Drafts', 'المسودات'],
        'nav_product_issues' => ['Product issues', 'مشاكل المنتجات'],
        'nav_bulk_operations' => ['Bulk operations', 'العمليات الجماعية'],
        'nav_inventory' => ['Inventory', 'المخزون'],
        'nav_overview' => ['Overview', 'نظرة عامة'],
        'nav_stock' => ['Stock', 'الكميات'],
        'nav_low_stock' => ['Low stock', 'مخزون منخفض'],
        'nav_movements' => ['Movement ledger', 'سجل الحركات'],
        'nav_warehouse_ops' => ['Warehouse operations', 'عمليات المستودع'],
        'nav_pricing' => ['Pricing', 'الأسعار'],
        'nav_scheduled_pricing' => ['Scheduled pricing', 'تغييرات مجدولة'],
        'nav_price_history' => ['Price history', 'سجل الأسعار'],
        'nav_fee_simulator' => ['Fee simulator', 'حاسبة العمولات'],
        'nav_fulfilment' => ['Fulfilment', 'التجهيز والشحن'],
        'nav_shipments' => ['Shipments', 'الشحنات'],
        'nav_picking' => ['Picking', 'التجميع'],
        'nav_packing' => ['Packing', 'التغليف'],
        'nav_shipping' => ['Shipping', 'الشحن'],
        'nav_exceptions' => ['Exceptions', 'الحالات الاستثنائية'],
        'nav_finance' => ['Finance', 'المالية'],
        'nav_transactions' => ['Transactions', 'المعاملات'],
        'nav_balance' => ['Balance', 'الرصيد'],
        'nav_payouts' => ['Payouts', 'السحوبات'],
        'nav_statements' => ['Statements', 'كشوف الحساب'],
        'nav_reconciliation' => ['Reconciliation', 'التسويات المالية'],
        'nav_fees' => ['Fees', 'العمولات والرسوم'],
        'nav_operations' => ['Operations', 'العمليات'],
        'nav_issue_center' => ['Issue Center', 'مركز المشاكل'],
        'nav_incidents' => ['Incidents', 'الأعطال'],
        'nav_automation_rules' => ['Automation rules', 'قواعد الأتمتة'],
        'nav_scheduled_ops' => ['Scheduled operations', 'عمليات مجدولة'],
        'nav_automation_history' => ['Automation history', 'سجل الأتمتة'],
        'nav_opportunities' => ['Opportunities', 'فرص التحسين'],
        'nav_growth' => ['Growth', 'النمو'],
        'nav_campaigns' => ['Campaigns', 'الحملات'],
        'nav_coupons' => ['Coupons', 'الكوبونات'],
        'nav_advertising' => ['Advertising', 'الإعلانات'],
        'nav_trust' => ['Trust', 'الموثوقية'],
        'nav_seller_performance' => ['Seller performance', 'أداء البائع'],
        'nav_account_health' => ['Account health', 'صحة الحساب'],
        'nav_sla' => ['SLA performance', 'مستوى الخدمة'],
        'nav_brand_registry' => ['Brand registry', 'سجل العلامات'],
        'nav_brand_authorization' => ['Brand authorization', 'تفويض العلامة'],
        'nav_brand_protection' => ['Brand protection', 'حماية العلامة'],
        'nav_compliance' => ['Compliance documents', 'مستندات الامتثال'],
        'nav_platform' => ['Platform', 'المنصة'],
        'nav_reports' => ['Reports', 'التقارير'],
        'nav_report_builder' => ['Report builder', 'منشئ التقارير'],
        'nav_exports' => ['Exports', 'الملفات المصدّرة'],
        'nav_connected_apps' => ['Connected apps', 'التطبيقات المرتبطة'],
        'nav_api' => ['API credentials', 'مفاتيح الـ API'],
        'nav_webhooks' => ['Webhooks', 'الويب هوك'],
        'nav_integration_health' => ['Integration health', 'صحة التكامل'],
        'nav_organization' => ['Organization', 'المؤسسة'],
        'nav_team' => ['Team', 'الفريق'],
        'nav_roles' => ['Roles & permissions', 'الأدوار والصلاحيات'],
        'nav_approvals' => ['Approvals', 'الموافقات'],
        'nav_audit' => ['Audit log', 'سجل التدقيق'],
        'nav_security' => ['Security', 'الأمان'],
        'nav_cases' => ['Cases', 'الحالات'],
        'nav_appeals' => ['Appeals', 'الاعتراضات'],

        // ── 2. buttons & actions ─────────────────────────────────────────
        'open' => ['Open', 'فتح'],
        'details' => ['Details', 'التفاصيل'],
        'retry' => ['Retry', 'إعادة المحاولة'],
        'refresh_tracking' => ['Refresh tracking', 'تحديث التتبّع'],
        'mark_packed' => ['Mark packed', 'تم التغليف'],
        'print_label' => ['Print label', 'طباعة البوليصة'],
        'print_labels' => ['Print labels', 'طباعة البوالص'],
        'print_invoice' => ['Print invoice', 'طباعة الفاتورة'],
        'create_shipment' => ['Create shipment', 'إنشاء شحنة'],
        'accept' => ['Accept', 'قبول'],
        'cancel_order' => ['Cancel order', 'إلغاء الطلب'],
        'keep_order' => ['Keep order', 'إبقاء الطلب'],
        'fix_product' => ['Fix product', 'إصلاح المنتج'],
        'restock' => ['Restock', 'تعزيز المخزون'],
        'adjust' => ['Adjust', 'تعديل'],
        'count' => ['Count', 'جرد'],
        'answer_returns' => ['Answer returns', 'الرد على المرتجعات'],
        'review_inventory' => ['Review inventory', 'مراجعة المخزون'],
        'open_reconciliation' => ['Open reconciliation', 'فتح التسوية'],
        'request_payout' => ['Request payout', 'طلب سحب'],
        'download_statement' => ['Download statement', 'تنزيل الكشف'],
        'download_errors' => ['Download errors', 'تنزيل الأخطاء'],
        'add_filter' => ['Add filter', 'إضافة فلتر'],
        'clear_all' => ['Clear all', 'مسح الكل'],
        'clear_all_filters' => ['Clear all filters', 'مسح كل الفلاتر'],
        'columns' => ['Columns', 'الأعمدة'],
        'save_current_view' => ['Save current view', 'حفظ العرض الحالي'],
        'export' => ['Export', 'تصدير'],
        'assign' => ['Assign…', 'إسناد…'],
        'snooze' => ['Snooze', 'تأجيل'],
        'resolve' => ['Resolve', 'إغلاق'],
        'open_full_page' => ['Open full page', 'فتح كصفحة كاملة'],
        'create_automation' => ['Create automation', 'إنشاء أتمتة'],
        'preview_matches' => ['Preview matches', 'معاينة المطابقات'],
        'save_and_activate' => ['Save & activate', 'حفظ وتنشيط'],
        'resume' => ['Resume', 'استئناف'],
        'undo' => ['Undo', 'تراجع'],
        'submit_for_verification' => ['Submit for verification', 'إرسال للتحقق'],
        'upload_document' => ['Upload document', 'رفع مستند'],
        'provide_evidence' => ['Provide evidence', 'تقديم إثبات'],
        'renew_document' => ['Renew document', 'تجديد المستند'],
        'renew_authorisation' => ['Renew authorisation', 'تجديد التفويض'],
        'join_campaign' => ['Join campaign', 'الانضمام للحملة'],
        'request_access' => ['Request access', 'طلب صلاحية'],
        'submit_appeal' => ['Submit appeal', 'تقديم اعتراض'],
        'revoke' => ['Revoke', 'إبطال'],
        'rotate' => ['Rotate', 'تدوير المفتاح'],
        'view_trail' => ['View trail', 'عرض السجل'],
        'view_affected_orders' => ['View affected orders', 'عرض الطلبات المتأثرة'],
        'apply' => ['Apply', 'تطبيق'],
        'remove_filter' => ['Remove filter', 'إزالة الفلتر'],
        'mark_all_read' => ['Mark all read', 'تعليم الكل كمقروء'],
        'open_issue_center' => ['Open issue center', 'فتح مركز المشاكل'],
        'open_search' => ['Open search', 'فتح البحث'],
        'resolve_shortage' => ['Resolve shortage', 'معالجة النقص'],
        'back_to_seller_home' => ['Back to Seller Home', 'العودة إلى لوحة البائع'],
        'select_row' => ['Select row', 'تحديد الصف'],
        'select_all_on_this_page' => ['Select all on this page', 'تحديد كل ما في هذه الصفحة'],

        // ── 3. statuses ──────────────────────────────────────────────────
        'under_review' => ['Under review', 'قيد المراجعة'],
        'out_of_stock' => ['Out of stock', 'نفد المخزون'],
        'low_stock' => ['Low stock', 'مخزون منخفض'],
        'healthy' => ['Healthy', 'سليم'],
        'discrepancy' => ['Discrepancy', 'فرق جرد'],
        'ready_to_ship' => ['Ready to ship', 'جاهز للشحن'],
        'packed' => ['Packed', 'تم التغليف'],
        'picking' => ['Picking', 'جاري التجميع'],
        'in_transit' => ['In transit', 'في الطريق'],
        'out_for_delivery' => ['Out for delivery', 'خرج للتسليم'],
        'late' => ['Late', 'متأخر'],
        'return_open' => ['Return open', 'مرتجع مفتوح'],
        'partially_completed' => ['Partially completed', 'مكتمل جزئياً'],
        'matched' => ['Matched', 'مطابق'],
        'unmatched' => ['Unmatched', 'غير مطابق'],
        'requires_review' => ['Requires review', 'يحتاج مراجعة'],
        'expiring_soon' => ['Expiring soon', 'ينتهي قريباً'],
        'monitoring' => ['Monitoring', 'قيد المراقبة'],
        'degraded' => ['Degraded', 'متأثر'],
        'watch' => ['Watch', 'تحت المراقبة'],
        'at_risk' => ['At risk', 'في خطر'],
        'no_data' => ['No data', 'لا توجد بيانات'],
        'unknown' => ['No data', 'لا توجد بيانات'],
        'cod' => ['COD', 'عند الاستلام'],
        'card' => ['Card', 'بطاقة'],
        'critical' => ['Critical', 'حرج'],
        'high' => ['High', 'مرتفع'],
        'medium' => ['Medium', 'متوسط'],
        'low' => ['Low', 'منخفض'],
        'label_created' => ['Label created', 'تم إنشاء البوليصة'],
        'stopped_by_marketplace' => ['Stopped by the marketplace', 'تم إيقافها من قبل السوق'],
        'more_information_required' => ['More information required', 'مطلوب معلومات إضافية'],
        'seller_fulfilled' => ['Seller fulfilled', 'تجهيز البائع'],

        // ── 4. brand relationships (never collapse these) ────────────────
        'brand_owner' => ['Verified brand owner', 'مالك علامة موثّق'],
        'brand_manufacturer' => ['Manufacturer', 'الجهة المصنّعة'],
        'brand_distributor' => ['Authorised distributor', 'موزّع معتمد'],
        'brand_seller' => ['Authorised seller', 'بائع معتمد'],
        'brand_pending' => ['Pending verification', 'بانتظار التحقق'],
        'brand_more_info' => ['More information required', 'مطلوب معلومات إضافية'],
        'brand_rejected' => ['Verification rejected', 'تم رفض التحقق'],
        'brand_expired' => ['Authorisation expired', 'انتهى التفويض'],

        // ── 5. empty states ──────────────────────────────────────────────
        'nothing_needs_attention' => ['Nothing needs attention', 'لا شيء يحتاج انتباهك'],
        'no_critical_issues' => ['No critical issues', 'لا مشاكل حرجة'],
        'everything_requiring_immediate_attention_is_currently_under_control' => [
            'Everything requiring immediate attention is currently under control.',
            'كل ما يحتاج تدخلاً فورياً تحت السيطرة حالياً.',
        ],
        'no_orders_yet' => ['No orders yet', 'لا طلبات بعد'],
        'orders_appear_here_as_soon_as_customers_buy' => [
            'Orders appear here as soon as customers buy.',
            'تظهر الطلبات هنا فور شراء العملاء.',
        ],
        'no_orders_match_these_filters' => ['No orders match these filters', 'لا طلبات تطابق هذه الفلاتر'],
        'adjust_or_clear_the_filters_to_see_more' => [
            'Adjust or clear the filters to see more.',
            'عدّل الفلاتر أو امسحها لعرض المزيد.',
        ],
        'no_products_yet' => ['No products yet', 'لا منتجات بعد'],
        'add_your_first_product_to_start_selling' => [
            'Add your first product to start selling.',
            'أضف أول منتج لتبدأ البيع.',
        ],
        'no_movements_recorded_in_this_period' => [
            'No movements recorded in this period',
            'لا حركات في هذه الفترة',
        ],
        'stock_changes_appear_here_with_the_balance_they_left_behind' => [
            'Stock changes appear here with the balance they left behind.',
            'تظهر تغييرات المخزون هنا مع الرصيد الناتج عنها.',
        ],
        'no_automations' => ['No automations', 'لا قواعد أتمتة'],
        'create_rules_to_handle_repetitive_operational_tasks_automatically' => [
            'Create rules to handle repetitive operational tasks automatically.',
            'أنشئ قواعد لتنفيذ المهام المتكررة تلقائياً.',
        ],
        'no_opportunities_detected' => ['No opportunities detected', 'لا فرص مرصودة'],
        'everything_matched' => ['Everything matched', 'كل شيء مطابق'],
        'no_brands_registered' => ['No brands registered', 'لا علامات مسجّلة'],
        'all_documents_approved' => ['All documents approved', 'كل المستندات مقبولة'],
        'you_are_up_to_date' => ["You're up to date", 'لا إشعارات جديدة'],
        'notifications_about_orders_stock_payouts_and_compliance_appear_here' => [
            'Notifications about orders, stock, payouts and compliance appear here.',
            'تظهر هنا إشعارات الطلبات والمخزون والسحوبات والامتثال.',
        ],
        'no_match_for' => ['No match for', 'لا نتائج لـ'],
        'orders_and_shipments_search_by_full_reference_try_an_order_number_a_tracking_code_or_an_sku' => [
            'Orders and shipments search by full reference. Try an order number, a tracking code or an SKU.',
            'البحث في الطلبات والشحنات يتم بالمرجع الكامل. جرّب رقم طلب أو رقم تتبّع أو SKU.',
        ],
        'search_is_unavailable_retry' => ['Search is unavailable — retry', 'البحث غير متاح — أعد المحاولة'],
        'see_all' => ['See all', 'عرض الكل'],

        // ── 6. errors & warnings ─────────────────────────────────────────
        'this_list_could_not_be_loaded' => ['This list could not be loaded', 'تعذّر تحميل هذه القائمة'],
        'the_orders_service_did_not_answer' => ['The orders service did not answer', 'لم تستجب خدمة الطلبات'],
        'some_carrier_data_could_not_be_loaded' => [
            'Some carrier data could not be loaded.',
            'تعذّر تحميل بعض بيانات الناقل.',
        ],
        'some_columns_are_hidden_by_your_role' => [
            'Some columns are hidden by your role.',
            'بعض الأعمدة مخفية بحسب دورك.',
        ],
        'you_do_not_have_access_to' => ["You don't have access to", 'لا تملك صلاحية'],
        'this_page_requires_the_permission' => ['This page requires the permission', 'تتطلب هذه الصفحة الصلاحية'],
        'ask_an_owner_or_manager_to_grant_it' => [
            'Ask an owner or manager to grant it.',
            'اطلب من المالك أو المدير منحك الصلاحية.',
        ],
        'this_page_requires_a_permission_your_role_does_not_have_ask_an_owner_or_manager_to_grant_it' => [
            'This page requires a permission your role does not have. Ask an owner or manager to grant it.',
            'تتطلب هذه الصفحة صلاحية لا يملكها دورك. اطلب من المالك أو المدير منحك إياها.',
        ],
        'a_reason_is_required_to_reject' => ['A reason is required to reject.', 'سبب الرفض مطلوب.'],
        'ship_by_sla_at_risk' => ['Ship-by SLA at risk', 'مهلة الشحن في خطر'],
        'breached_by' => ['Breached by', 'تجاوز بـ'],
        'left' => ['left', 'يتبقى'],
        'selection_cleared_filters_changed' => [
            'Selection cleared — filters changed',
            'أُلغي التحديد — تغيّرت الفلاتر',
        ],
        'no_comparable_data_in_the_previous_period' => [
            'No comparable data in the previous period',
            'لا توجد بيانات مقارنة في الفترة السابقة',
        ],

        // ── 7. disclaimers (verbatim, required) ──────────────────────────
        'disclaimer_fee_simulator' => [
            'Estimated values based on current marketplace fee rules. Actual fees are calculated at the time of sale.',
            'قيم تقديرية وفق قواعد العمولات الحالية في السوق. تُحسب العمولات الفعلية عند إتمام البيع.',
        ],
        'disclaimer_coverage' => [
            'Coverage is available stock divided by the average daily sales of the last 14 days.',
            'التغطية هي المخزون المتاح مقسوماً على متوسط البيع اليومي لآخر ١٤ يوماً.',
        ],
        'disclaimer_customer_contact' => [
            'Full contact details are released to the carrier at pickup.',
            'تُسلَّم بيانات التواصل الكاملة للناقل عند الاستلام.',
        ],
        'disclaimer_api_secret' => [
            'This is the only time the secret is shown.',
            'هذه المرة الوحيدة التي يُعرض فيها المفتاح السري.',
        ],
        'disclaimer_claim_declaration' => [
            'False claims can suspend your account.',
            'البيانات غير الصحيحة قد تؤدي إلى إيقاف حسابك.',
        ],
        'disclaimer_return_window' => [
            "Approved automatically in the buyer's favour if unanswered.",
            'تُقبل تلقائياً لمصلحة المشتري إذا لم يتم الرد.',
        ],

        // ── 8. shell chrome ──────────────────────────────────────────────
        'seller_center' => ['Seller Center', 'مركز البائع'],
        'seller_id' => ['Seller ID', 'رقم البائع'],
        'search_orders_products_shipments_finance' => [
            'Search orders, products, shipments, finance…',
            'ابحث في الطلبات والمنتجات والشحنات والمالية…',
        ],
        'order_phone_tracking_sku' => ['Order, phone, tracking, SKU', 'رقم الطلب أو الهاتف أو التتبّع أو SKU'],
        'table_density' => ['Table density', 'كثافة الجدول'],
        'compact' => ['Compact', 'مضغوط'],
        'comfortable' => ['Comfortable', 'مريح'],
        'commands' => ['Commands', 'الأوامر'],
        'sections' => ['Sections', 'الأقسام'],
        'move' => ['move', 'تنقّل'],
        'jump_to_a_section' => ['Jump to a section', 'الانتقال إلى قسم'],
        'close_the_top_overlay' => ['Close the top overlay', 'إغلاق الطبقة العليا'],
        'move_and_open_in_search' => ['Move and open in search', 'التنقّل والفتح في البحث'],
        'keyboard_shortcuts' => ['Keyboard shortcuts', 'اختصارات لوحة المفاتيح'],
        'language_and_numerals' => ['Language & numerals', 'اللغة والأرقام'],
        'notification_preferences' => ['Notification preferences', 'تفضيلات الإشعارات'],
        'my_profile' => ['My profile', 'ملفي الشخصي'],
        'store_profile' => ['Store profile', 'ملف المتجر'],
        'store_settings' => ['Store settings', 'إعدادات المتجر'],
        'switch_staff_account' => ['Switch staff account', 'تبديل حساب الموظف'],
        'go_to_control_tower' => ['Go to Control Tower', 'الذهاب إلى مركز التحكم'],
        'open_ship_today_queue' => ['Open ship-today queue', 'فتح قائمة الشحن اليوم'],
        'create_stock_adjustment' => ['Create stock adjustment', 'إنشاء تعديل مخزون'],
        'new_report' => ['New report', 'تقرير جديد'],
        'rows_per_page' => ['Rows per page', 'صفوف في الصفحة'],
        'previous_page' => ['Previous page', 'الصفحة السابقة'],
        'next_page' => ['Next page', 'الصفحة التالية'],
        'choose_a_file_or_drop_it_here' => ['Choose a file or drop it here', 'اختر ملفاً أو أفلته هنا'],
        'impact' => ['Impact', 'الأثر'],
        'normal_operations_stay_quiet_problems_and_required_actions_become_prominent' => [
            'Normal operations stay quiet. Problems and required actions become prominent.',
            'العمليات الطبيعية تبقى هادئة. المشاكل والإجراءات المطلوبة تظهر بوضوح.',
        ],
        'every_problem_carries_a_severity_an_affected_count_a_deadline_one_action_and_a_direct_drill_down' => [
            'Every problem carries a severity, an affected count, a deadline, one action and a direct drill-down.',
            'كل مشكلة تحمل درجة خطورة وعدد المتأثرين ومهلة وإجراءً واحداً ورابطاً مباشراً للتفاصيل.',
        ],
        'how_this_panel_works' => ['How this panel works', 'كيف تعمل هذه اللوحة'],

        // ── what the detectors call their findings, and the health domains ──
        'insight_body_order_stuck' => ['Order :order has sat in :status for :elapsed.', 'الطلب :order بقي في حالة :status لمدة :elapsed.'],
        'insight_body_order_late' => ['Order :order is :elapsed past its ship-by time.', 'الطلب :order تجاوز موعد شحنه بـ :elapsed.'],
        'insight_body_order_due_soon' => ['Order :order must ship within :elapsed.', 'يجب شحن الطلب :order خلال :elapsed.'],
        'insight_body_refund_overdue' => ['The refund request on order :order has been waiting :elapsed for an answer.', 'طلب الاسترداد على الطلب :order ينتظر رداً منذ :elapsed.'],
        'insight_body_shipments_silent_one' => ['1 shipment has not moved for :elapsed, holding :value.', 'شحنة واحدة لم تتحرّك منذ :elapsed، وتحتجز :value.'],
        'insight_body_shipments_silent' => [':count shipments have not moved for :elapsed, holding :value.', ':count شحنات لم تتحرّك منذ :elapsed، وتحتجز :value.'],
        'insight_body_product_rejected' => ['":product" was rejected by the marketplace. Reason: :reason', 'رُفض المنتج «:product» من السوق. السبب: :reason'],
        'no_reason_was_recorded' => ['no reason was recorded', 'لم يُسجَّل سبب'],
        'insight_body_listing_incomplete' => ['":product" scores :score/100 — missing :missing.', 'المنتج «:product» حصل على :score/100 — ينقصه :missing.'],
        'insight_body_out_of_stock' => ['":product" is out of stock and sold :sold units in the last :days days.', 'نفد مخزون «:product» وقد بيع منه :sold وحدة خلال آخر :days يوماً.'],
        'insight_body_running_out' => ['":product" has :stock units left — about :cover days of cover.', 'تبقّى من «:product» :stock وحدة — نحو :cover يوماً من التغطية.'],
        'insight_body_brand' => [':brand covers :count of your listings and has no authorisation on file.', 'تغطي العلامة :brand :count من منتجاتك ولا يوجد تفويض مسجّل لها.'],
        'images' => ['images', 'الصور'],
        'details' => ['description', 'الوصف'],
        'meta' => ['search text', 'نص البحث'],
        'unit' => ['unit', 'الوحدة'],
        'insight_body_order_state_one' => ['1 order is :state, holding :value.', 'طلب واحد :state، ويحتجز :value.'],
        'insight_body_order_state' => [':count orders are :state, holding :value.', ':count طلبات :state، وتحتجز :value.'],
        'insight_body_returns_waiting_one' => ['1 approved return has not been processed for over :hours hours.', 'مرتجع واحد مقبول لم يُعالَج منذ أكثر من :hours ساعة.'],
        'insight_body_returns_waiting' => [':count approved returns have not been processed for over :hours hours.', ':count مرتجعات مقبولة لم تُعالَج منذ أكثر من :hours ساعة.'],
        'insight_body_duplicate_barcodes_one' => ['1 barcode is used by more than one product, so scans resolve to the wrong item.', 'باركود واحد مستخدم لأكثر من منتج، فتشير عمليات المسح إلى الصنف الخطأ.'],
        'insight_body_duplicate_barcodes' => [':count barcodes are used by more than one product, so scans resolve to the wrong item.', ':count باركودات مستخدمة لأكثر من منتج، فتشير عمليات المسح إلى الصنف الخطأ.'],
        'insight_body_missing_attributes_one' => ['1 product is missing a required attribute — :attribute. It will be rejected on submission.', 'منتج واحد تنقصه خاصية مطلوبة — :attribute. سيُرفض عند الإرسال.'],
        'insight_body_missing_attributes' => [':count products are missing required attributes, starting with :attribute. They will be rejected on submission.', ':count منتجات تنقصها خصائص مطلوبة، أولها :attribute. ستُرفض عند الإرسال.'],
        'insight_body_price_moved' => ['Price moved from :from to :to — a :percent% change, made by :source.', 'تغيّر السعر من :from إلى :to — بنسبة :percent%، عبر :source.'],
        'insight_body_below_cost_one' => ['1 product is priced below its recorded cost — selling the stock on hand would lose :value.', 'منتج واحد سعره دون تكلفته المسجّلة — بيع المخزون الحالي سيخسر :value.'],
        'insight_body_below_cost' => [':count products are priced below their recorded cost — selling the stock on hand would lose :value.', ':count منتجات أسعارها دون تكلفتها المسجّلة — بيع المخزون الحالي سيخسر :value.'],
        'manual' => ['Manual', 'يدوي'],
        'bulk' => ['Bulk', 'جماعي'],
        'api' => ['API', 'API'],
        'promotion' => ['Promotion', 'عرض ترويجي'],
        'automation' => ['Automation', 'أتمتة'],
        'seller_ui' => ['Seller panel', 'لوحة البائع'],
        'insight_body_stale_inventory_one' => ['1 product has not sold in :days days, holding :value in stock.', 'منتج واحد لم يُبَع خلال :days يوماً، ويحتجز :value في المخزون.'],
        'insight_body_stale_inventory' => [':count products have not sold in :days days, holding :value in stock.', ':count منتجات لم تُبَع خلال :days يوماً، وتحتجز :value في المخزون.'],
        'insight_body_stale_inventory_one_no_cost' => ['1 product has not sold in :days days.', 'منتج واحد لم يُبَع خلال :days يوماً.'],
        'insight_body_stale_inventory_no_cost' => [':count products have not sold in :days days.', ':count منتجات لم تُبَع خلال :days يوماً.'],
        'insight_body_delivered_without_earning_one' => ['1 delivered order line has no earning recorded — :value is uncredited.', 'سطر طلب مُسلّم واحد بلا أرباح مسجّلة — :value غير مقيّدة.'],
        'insight_body_delivered_without_earning' => [':count delivered order lines have no earning recorded — :value is uncredited.', ':count سطر طلب مُسلّم بلا أرباح مسجّلة — :value غير مقيّدة.'],
        'insight_brand_listings_blocked' => ['Listings blocked by brand authorisation', 'منتجات موقوفة بسبب تفويض العلامة'],
        'insight_brand_not_claimed' => ['Brand has no claim on file', 'لا يوجد تفويض مسجّل لهذه العلامة'],
        'insight_delivered_without_earning' => ['Delivered orders with no earning recorded', 'طلبات سُلّمت ولم تُسجّل أرباحها'],
        'insight_duplicate_barcodes' => ['Duplicate barcodes in the catalogue', 'باركودات مكررة في الكتالوج'],
        'insight_inventory_not_moving' => ['Stock that has not moved', 'مخزون لم يتحرّك'],
        'insight_listing_hidden_with_stock' => ['Hidden listing that has stock', 'منتج مخفي ولديه مخزون'],
        'insight_listing_incomplete' => ['Listing is missing information', 'المنتج ينقصه معلومات'],
        'insight_listing_live_without_stock' => ['Listing is live with no stock', 'منتج معروض بلا مخزون'],
        'insight_missing_required_attributes' => ['Missing required attributes', 'خصائص مطلوبة ناقصة'],
        'insight_order_due_soon' => ['Orders due to ship soon', 'طلبات يقترب موعد شحنها'],
        'insight_order_late' => ['Orders past their ship-by time', 'طلبات تجاوزت موعد شحنها'],
        'insight_order_stuck' => ['Order has not moved', 'طلب لم يتحرّك'],
        'insight_out_of_stock' => ['Out of stock', 'نفد المخزون'],
        'insight_price_below_cost' => ['Price is below cost', 'السعر أقل من التكلفة'],
        'insight_price_dropped_sharply' => ['Price dropped sharply', 'انخفض السعر بشدة'],
        'insight_price_rose_sharply' => ['Price rose sharply', 'ارتفع السعر بشدة'],
        'insight_product_rejected' => ['Product rejected by the marketplace', 'رفض السوق المنتج'],
        'insight_refund_response_overdue' => ['Refund response is overdue', 'تأخر الرد على طلب الاسترداد'],
        'insight_returns_awaiting_processing' => ['Returns awaiting processing', 'مرتجعات بانتظار المعالجة'],
        'insight_running_out' => ['Running out of stock', 'المخزون يوشك على النفاد'],
        'insight_shipments_not_moving' => ['Shipments have not moved', 'شحنات لم تتحرّك'],
        'orders' => ['Orders', 'الطلبات'],
        'inventory' => ['Inventory', 'المخزون'],
        'catalog' => ['Catalog', 'الكتالوج'],
        'pricing' => ['Pricing', 'الأسعار'],
        'returns' => ['Returns', 'المرتجعات'],
        'shipping' => ['Shipping', 'الشحن'],
        'finance' => ['Finance', 'المالية'],
        'integrations' => ['Integrations', 'التكاملات'],
        'products' => ['Products', 'المنتجات'],

        // ── sentences with placeholders (see Copy::line) ─────────────────
        'n_minutes' => [':count min', ':count دقيقة'],
        'n_hours' => [':counth', ':count ساعة'],
        'n_hours_n_minutes' => [':hoursh :minutesm', ':hours ساعة و:minutes دقيقة'],
        'n_days' => [':countd', ':count يوم'],
        'n_days_n_hours' => [':daysd :hoursh', ':days يوم و:hours ساعة'],
        'breached_by_time' => ['Breached by :time', 'تجاوز بـ :time'],
        'time_left' => [':time left', 'يتبقى :time'],
        'showing_range' => [':from–:to of :total', ':from–:to من :total'],
        'one_issue_n_affected' => ['1 issue · :affected affected', 'مشكلة واحدة · :affected متأثر'],
        'n_issues_n_affected' => [':count issues · :affected affected', ':count مشاكل · :affected متأثر'],
        'one_resolved' => ['1 resolved', 'أُغلقت واحدة'],
        'n_resolved' => [':count resolved', 'أُغلقت :count'],
        'n_open_n_due_today' => [':open open · :due due today', ':open مفتوحة · :due مستحقة اليوم'],
        'n_affected' => [':count affected', ':count متأثر'],
        'n_orders' => [':count orders', ':count طلب'],
        'n_products' => [':count products', ':count منتج'],
        'n_issues' => [':count issues', ':count مشكلة'],
        'n_skus' => [':count SKUs', ':count رمز منتج'],
        'n_movements' => [':count movements', ':count حركة'],
        'across_n_skus' => ['across :count SKUs', 'عبر :count رمز منتج'],
        'at_or_under_n_units' => ['at or under :count units', 'عند أو دون :count وحدة'],
        'n_lines_running_low' => [':count lines are running low', ':count أسطر توشك على النفاد'],
        'review_n_lines' => ['Review :count lines', 'مراجعة :count سطر'],
        'n_of_limit' => [':value of a :limit limit', ':value من حد :limit'],
        'n_days_cover' => [':count days', ':count يوم'],
        'value_of_limit' => [':value of :limit', ':value من :limit'],
        'impact_n' => ['Impact :score', 'الأثر :score'],
        'detected_at' => ['Detected :time', 'رُصد :time'],
        'n_sections_hidden_by_your_role' => [':count sections are hidden by your role', ':count أقسام مخفية بحسب دورك'],
        'this_issue_affects_n' => ['This issue affects :count :entity.', 'تؤثر هذه المشكلة على :count :entity.'],
        'open_for_n_hours' => ['Open for :count hours', 'مفتوحة منذ :count ساعة'],
        'nothing_needs_attention_body' => ['No critical issues, no SLA risk and no financial exceptions in the last check at :time. Monitoring continues.', 'لا مشاكل حرجة ولا مخاطر على مستوى الخدمة ولا استثناءات مالية في آخر فحص :time. المراقبة مستمرة.'],
        'n_items_payment' => [':count items · :payment', ':count عناصر · :payment'],
        'sku_and_cover' => [':sku · :cover', ':sku · :cover'],
        'sku_and_stock' => [':sku · stock :stock', ':sku · المخزون :stock'],

        // ── wave 2 · the core operations screens ─────────────────────────
        'sla' => ['SLA', 'مستوى الخدمة'],
        'sla_risk' => ['SLA risk', 'مخاطر مستوى الخدمة'],
        'sla_at_risk' => ['SLA at risk', 'مستوى الخدمة في خطر'],
        'sla_risk_today' => ['SLA risk today', 'مخاطر مستوى الخدمة اليوم'],
        'pos' => ['POS', 'نقطة البيع'],
        'sku' => ['SKU', 'رمز المنتج'],
        'skus' => ['SKUs', 'رموز المنتجات'],
        'cod_only' => ['COD only', 'الدفع عند الاستلام فقط'],
        'no_decimal_places_in_syp' => ['No decimal places in SYP', 'بدون كسور عشرية بالليرة السورية'],
        'name_sku_barcode' => ['Name, SKU, barcode', 'الاسم أو SKU أو الباركود'],
        'of' => ['of', 'من'],
        'to' => ['to', 'إلى'],
        'by' => ['by', 'بواسطة'],
        'affected' => ['affected', 'متأثر'],
        'issues' => ['issues', 'مشاكل'],
        'issue' => ['Issue', 'مشكلة'],
        'items' => ['items', 'عناصر'],
        'lines' => ['lines', 'أسطر'],
        'days' => ['days', 'أيام'],
        'hours' => ['hours', 'ساعات'],
        'units' => ['units', 'وحدات'],
        'vs_prev' => ['vs prev', 'مقارنة بالسابق'],
        'left' => ['left', 'متبقٍ'],
        'account_health' => ['Account health', 'صحة الحساب'],
        'across' => ['across', 'عبر'],
        'at_or_under' => ['at or under', 'عند أو دون'],
        'available' => ['Available', 'المتاح'],
        'awaiting_shipment' => ['Awaiting shipment', 'بانتظار الشحن'],
        'brand' => ['Brand', 'العلامة'],
        'bulk_import' => ['Bulk import', 'استيراد جماعي'],
        'cancellation' => ['Cancellation', 'الإلغاء'],
        'carrier' => ['Carrier', 'الناقل'],
        'category' => ['Category', 'الفئة'],
        'change' => ['Change', 'التغيير'],
        'city' => ['City', 'المدينة'],
        'clear' => ['Clear', 'مسح'],
        'close' => ['Close', 'إغلاق'],
        'commission' => ['Commission', 'العمولة'],
        'compare_previous' => ['Compare previous', 'مقارنة بالسابق'],
        'coverage' => ['Coverage', 'التغطية'],
        'customer' => ['Customer', 'العميل'],
        'customer_and_delivery' => ['Customer & delivery', 'العميل والتوصيل'],
        'customer_pays_cod' => ['Customer pays (COD)', 'يدفع العميل (عند الاستلام)'],
        'daily_sales' => ['Daily sales', 'المبيع اليومي'],
        'detected' => ['Detected', 'رُصد'],
        'detected_by' => ['Detected by', 'رصده'],
        'discount' => ['Discount', 'الخصم'],
        'due' => ['Due', 'الاستحقاق'],
        'due_today' => ['Due today', 'مستحق اليوم'],
        'fulfilment' => ['Fulfilment', 'التجهيز'],
        'fulfilment_and_shipping' => ['Fulfilment & shipping', 'التجهيز والشحن'],
        'gross' => ['Gross', 'الإجمالي'],
        'held_by_open_orders' => ['held by open orders', 'محجوز بطلبات مفتوحة'],
        'impact_score' => ['Impact score', 'درجة الأثر'],
        'inventory_overview' => ['Inventory overview', 'نظرة عامة على المخزون'],
        'items_subtotal' => ['Items subtotal', 'مجموع العناصر'],
        'line' => ['Line', 'السطر'],
        'listing_quality' => ['Listing quality', 'جودة الإدراج'],
        'low_stock_lines' => ['Low stock lines', 'أسطر مخزون منخفض'],
        'manage_order' => ['Manage order', 'إدارة الطلب'],
        'marketplace' => ['Marketplace', 'السوق'],
        'met' => ['Met', 'تم الالتزام'],
        'model' => ['Model', 'النموذج'],
        'movements' => ['movements', 'حركات'],
        'net_to_balance' => ['Net to balance', 'الصافي إلى الرصيد'],
        'on_time' => ['On time', 'في الوقت'],
        'open_for' => ['Open for', 'مفتوحة منذ'],
        'order' => ['Order', 'الطلب'],
        'order_total' => ['Order total', 'إجمالي الطلب'],
        'paid_out' => ['Paid out', 'المدفوع'],
        'payment' => ['Payment', 'الدفع'],
        'payment_status' => ['Payment status', 'حالة الدفع'],
        'payout' => ['Payout', 'السحب'],
        'pending_clearance' => ['Pending clearance', 'قيد التصفية'],
        'phone' => ['Phone', 'الهاتف'],
        'physical' => ['Physical', 'الفعلي'],
        'placed' => ['Placed', 'تاريخ الطلب'],
        'previous' => ['Previous', 'السابق'],
        'price' => ['Price', 'السعر'],
        'product' => ['Product', 'المنتج'],
        'promised_delivery' => ['Promised delivery', 'التسليم الموعود'],
        'qty' => ['Qty', 'الكمية'],
        'reason' => ['Reason', 'السبب'],
        'reference' => ['Reference', 'المرجع'],
        'refund_rate' => ['Refund rate', 'معدل الاسترداد'],
        'reserved' => ['Reserved', 'محجوز'],
        'reserved_open_payout' => ['Reserved (open payout)', 'محجوز (طلب سحب مفتوح)'],
        'return_rate' => ['Return rate', 'معدل الإرجاع'],
        'revenue' => ['Revenue', 'الإيراد'],
        'reversed' => ['Reversed', 'معكوس'],
        'review' => ['Review', 'مراجعة'],
        'running_low' => ['Running low', 'يوشك على النفاد'],
        'sales_trend' => ['Sales trend', 'اتجاه المبيعات'],
        'search_issues' => ['Search issues', 'ابحث في المشاكل'],
        'severity' => ['Severity', 'الخطورة'],
        'ship_by' => ['Ship by', 'الشحن قبل'],
        'shipping_charged' => ['Shipping charged', 'الشحن المحصّل'],
        'state' => ['State', 'الحالة'],
        'status' => ['Status', 'الحالة'],
        'stock' => ['Stock', 'المخزون'],
        'system_health' => ['System health', 'صحة النظام'],
        'this_period' => ['This period', 'هذه الفترة'],
        'timeline' => ['Timeline', 'الخط الزمني'],
        'timestamp' => ['Timestamp', 'الوقت'],
        'todays_queue' => ['Today\'s queue', 'قائمة اليوم'],
        'top_products' => ['Top products', 'أفضل المنتجات'],
        'total' => ['Total', 'الإجمالي'],
        'type' => ['Type', 'النوع'],
        'unit' => ['Unit', 'الوحدة'],
        'units_on_hand' => ['Units on hand', 'الوحدات المتوفرة'],
        'walk_in_customer' => ['Walk-in customer', 'عميل مباشر'],
        'what_happened' => ['What happened', 'ما الذي حدث'],
        'what_needs_you_today' => ['What needs you today', 'ما يحتاج انتباهك اليوم'],
        'why_it_matters' => ['Why it matters', 'لماذا يهم'],
        'withdrawable_now' => ['Withdrawable now', 'قابل للسحب الآن'],
        'your_earnings' => ['Your earnings', 'أرباحك'],
        'selling_price' => ['Selling price', 'سعر البيع'],
        'operations_control_tower' => ['Operations control tower', 'مركز التحكم بالعمليات'],
        'critical_now' => ['Critical now', 'حرج الآن'],
        'needs_action_today' => ['Needs action today', 'يحتاج إجراءً اليوم'],
        'fulfilment_exceptions' => ['Fulfilment exceptions', 'استثناءات التجهيز'],
        'returns_requiring_action' => ['Returns requiring action', 'مرتجعات تحتاج إجراءً'],
        'inventory_risk' => ['Inventory risk', 'مخاطر المخزون'],
        'financial_exceptions' => ['Financial exceptions', 'استثناءات مالية'],
        'catalog_and_pricing' => ['Catalog and pricing', 'الكتالوج والأسعار'],
        'fixed_automatically_last_24h' => ['Fixed automatically · last 24h', 'أُصلح تلقائياً · آخر ٢٤ ساعة'],
        'raised_from' => ['Raised from', 'رُفعت من'],
        'severity_raised_from' => ['Severity raised from', 'رُفعت الخطورة من'],
        'resolved_automatically' => ['Resolved automatically', 'أُغلقت تلقائياً'],
        'needs_immediate_attention' => ['Needs immediate attention', 'يحتاج تدخلاً فورياً'],
        'orders_inside_the_ship_by_window' => ['Orders inside the ship-by window', 'طلبات داخل مهلة الشحن'],
        'accepted_and_not_yet_shipped' => ['Accepted and not yet shipped', 'مقبولة ولم تُشحن بعد'],
        'awaiting_your_answer' => ['Awaiting your answer', 'بانتظار ردّك'],
        'returns_to_answer' => ['Returns to answer', 'مرتجعات تحتاج رداً'],
        'open_control_tower' => ['Open Control Tower', 'فتح مركز التحكم'],
        'open_order_queue' => ['Open order queue', 'فتح قائمة الطلبات'],
        'open_order' => ['Open order', 'فتح الطلب'],
        'open_refund' => ['Open refund', 'فتح الاسترداد'],
        'open_statement' => ['Open statement', 'فتح الكشف'],
        'open_brand_registry' => ['Open brand registry', 'فتح سجل العلامات'],
        'fix_products' => ['Fix products', 'إصلاح المنتجات'],
        'sections_in_server_reading_order_empty_ones_hidden' => ['sections in server reading order, empty ones hidden', 'الأقسام بترتيب الخادم، والفارغة مخفية'],
        'sections_are_hidden_by_your_role' => ['sections are hidden by your role', 'أقسام مخفية بحسب دورك'],
        'monitoring_continues' => ['Monitoring continues.', 'المراقبة مستمرة.'],
        'control_tower_could_not_load' => ['Control Tower could not load', 'تعذّر تحميل مركز التحكم'],
        'the_operations_service_did_not_answer_order_and_inventory_screens_are_unaffected_this_page_only_aggregates_them' => ['The operations service did not answer. Order and inventory screens are unaffected — this page only aggregates them.', 'لم تستجب خدمة العمليات. شاشات الطلبات والمخزون غير متأثرة — هذه الصفحة تجمّعها فقط.'],
        'no_critical_issues_no_sla_risk_and_no_financial_exceptions_in_the_last_check_at' => ['No critical issues, no SLA risk and no financial exceptions in the last check at', 'لا مشاكل حرجة ولا مخاطر على مستوى الخدمة ولا استثناءات مالية في آخر فحص'],
        'no_sales_in_this_period' => ['No sales in this period', 'لا مبيعات في هذه الفترة'],
        'sales_appear_here_once_orders_are_delivered' => ['Sales appear here once orders are delivered.', 'تظهر المبيعات هنا بعد تسليم الطلبات.'],
        'the_products_that_sell_appear_here_ranked_by_revenue' => ['The products that sell appear here, ranked by revenue.', 'تظهر هنا المنتجات التي تُباع مرتبة حسب الإيراد.'],
        'the_balance_service_did_not_answer' => ['The balance service did not answer.', 'لم تستجب خدمة الرصيد.'],
        'no_products_match_these_filters' => ['No products match these filters', 'لا منتجات تطابق هذه الفلاتر'],
        'no_issues_match_these_filters' => ['No issues match these filters', 'لا مشاكل تطابق هذه الفلاتر'],
        'no_movements_match_these_filters' => ['No movements match these filters', 'لا حركات تطابق هذه الفلاتر'],
        'no_stock_matches_these_filters' => ['No stock matches these filters', 'لا مخزون يطابق هذه الفلاتر'],
        'no_stock_to_track_yet' => ['No stock to track yet', 'لا مخزون لتتبعه بعد'],
        'physical_products_appear_here_with_their_cover_and_their_movements' => ['Physical products appear here with their cover and their movements.', 'تظهر المنتجات الفعلية هنا مع تغطيتها وحركاتها.'],
        'lines_are_running_low' => ['lines are running low', 'أسطر توشك على النفاد'],
        'not_sellable_right_now' => ['not sellable right now', 'غير قابل للبيع حالياً'],
        'every_change_carries_the_balance_it_left_behind_the_log_reads_without_replaying_it' => ['Every change carries the balance it left behind — the log reads without replaying it.', 'كل تغيير يحمل الرصيد الناتج عنه — يُقرأ السجل دون إعادة تشغيله.'],
        'nothing_resolved_in_this_period' => ['Nothing resolved in this period', 'لا شيء أُغلق في هذه الفترة'],
        'resolved_issues_stay_here_with_what_closed_them' => ['Resolved issues stay here with what closed them.', 'تبقى المشاكل المُغلقة هنا مع ما أغلقها.'],
        'detection_runs_continuously_and_writes_only_what_it_finds' => ['Detection runs continuously and writes only what it finds.', 'يعمل الرصد باستمرار ولا يكتب إلا ما يجده.'],
        'nothing_recorded_yet' => ['Nothing recorded yet', 'لا شيء مسجّل بعد'],
        'every_status_change_appears_here_with_who_made_it' => ['Every status change appears here with who made it.', 'يظهر كل تغيير حالة هنا مع من قام به.'],
        'closes_when_the_condition_stops_being_true' => ['Closes when the condition stops being true', 'تُغلق عندما يتوقف الشرط عن الصحة'],
        'this_issue_affects' => ['This issue affects', 'تؤثر هذه المشكلة على'],
        'estimated_exposure' => ['Estimated exposure', 'التعرّض التقديري'],
        'impact_is_scored_against_this_shops_own_business_not_an_absolute_figure' => ['Impact is scored against this shop\'s own business, not an absolute figure.', 'تُحسب درجة الأثر مقارنة بأعمال هذا المتجر نفسه، لا برقم مطلق.'],
        'affected_items' => ['Affected items', 'العناصر المتأثرة'],
        'recorded_in_the_ledger' => ['Recorded in the ledger', 'مسجّل في الدفتر'],
        'not_settled_yet_this_is_what_it_will_be' => ['Not settled yet — this is what it will be.', 'لم تُسوَّ بعد — هذا ما ستكون عليه.'],
        'this_order_is_inside_its_ship_by_window_the_countdown_is_measured_from_when_it_was_placed' => ['This order is inside its ship-by window. The countdown is measured from when it was placed.', 'هذا الطلب داخل مهلة الشحن. يُحسب العد التنازلي من وقت الطلب.'],
        'assigned' => ['Assigned', 'مُسند إلى'],
        'system' => ['System', 'النظام'],
        'owner' => ['Owner', 'المالك'],
        'staff' => ['Staff', 'موظف'],
        'more' => ['More', 'المزيد'],
        'menu' => ['Menu', 'القائمة'],
        'help' => ['Help', 'المساعدة'],
        'search' => ['Search', 'بحث'],
        'settings' => ['Settings', 'الإعدادات'],
        'support' => ['Support', 'الدعم'],
        'notifications' => ['Notifications', 'الإشعارات'],
        'account' => ['Account', 'الحساب'],
        'language' => ['Language', 'اللغة'],
        'sign_out' => ['Sign out', 'تسجيل الخروج'],
        'back' => ['Back', 'رجوع'],
        'breadcrumb' => ['Breadcrumb', 'مسار التنقل'],
        'selected' => ['selected', 'محدد'],
        'yes' => ['Yes', 'نعم'],
        'no' => ['No', 'لا'],
        'any' => ['Any', 'أي'],
        'all' => ['All', 'الكل'],
        'access_denied' => ['Access denied', 'الوصول مرفوض'],

        // ── wave 3 · automation (handoff 08 A1–A5, 12) ────────────────────
        'rule' => ['Rule', 'القاعدة'],
        'rules' => ['Rules', 'القواعد'],
        'trigger' => ['Trigger', 'المُشغِّل'],
        'action' => ['Action', 'الإجراء'],
        'scope' => ['Scope', 'النطاق'],
        'limits' => ['Limits', 'الحدود'],
        'when' => ['When', 'عندما'],
        'then' => ['Then', 'عندها'],
        'runs' => ['Runs', 'مرات التشغيل'],
        'applied' => ['Applied', 'طُبِّق'],
        'matched' => ['Matched', 'مطابق'],
        'skipped' => ['Skipped', 'مُتخطّى'],
        'failed' => ['Failed', 'فشل'],
        'result' => ['Result', 'النتيجة'],
        'duration' => ['Duration', 'المدة'],
        'time' => ['Time', 'الوقت'],
        'automation' => ['Automation', 'الأتمتة'],
        'last_run' => ['Last run', 'آخر تشغيل'],
        'success_rate' => ['Success rate', 'نسبة النجاح'],
        'pause' => ['Pause', 'إيقاف مؤقت'],
        'resume' => ['Resume', 'استئناف'],
        'activate' => ['Activate', 'تفعيل'],
        'undo' => ['Undo', 'تراجع'],
        'undone' => ['Undone', 'تم التراجع'],
        'run_now' => ['Run now', 'شغّل الآن'],
        'run_preview' => ['Preview', 'معاينة'],
        'preview_matches' => ['Preview matches', 'معاينة المطابقات'],
        'would_match' => ['Would match', 'سيطابق'],
        'would_apply' => ['Would apply', 'سيُطبَّق'],
        'before' => ['Before', 'قبل'],
        'after' => ['After', 'بعد'],
        'save' => ['Save', 'حفظ'],
        'save_and_activate' => ['Save and activate', 'حفظ وتفعيل'],
        'save_paused' => ['Save paused', 'حفظ موقوفاً'],
        'delete_rule' => ['Delete rule', 'حذف القاعدة'],
        'edit_automation' => ['Edit automation', 'تعديل الأتمتة'],
        'create_automation' => ['Create automation', 'إنشاء أتمتة'],
        'rule_name' => ['Rule name', 'اسم القاعدة'],
        'the_rule' => ['The rule', 'القاعدة'],
        'in_plain_words' => ['In plain words', 'بالكلمات الواضحة'],
        'what_it_has_done' => ['What it has done', 'ما الذي فعلته'],
        'whole_catalogue' => ['Whole catalogue', 'كامل الكتالوج'],
        'contact_support' => ['Contact support', 'تواصل مع الدعم'],
        'stopped_by_the_marketplace' => ['Stopped by the marketplace', 'أوقفها السوق'],
        'a_deleted_rule' => ['A deleted rule', 'قاعدة محذوفة'],
        'back_to_the_rule' => ['Back to the rule', 'العودة إلى القاعدة'],
        'max_actions_per_run' => ['Most changes per run', 'أقصى عدد تغييرات في التشغيلة'],
        'cooldown_minutes' => ['Wait between runs (minutes)', 'الانتظار بين التشغيلات (بالدقائق)'],
        'comma_separated_ids' => ['Ids separated by commas', 'معرّفات مفصولة بفواصل'],
        'what_this_rule_is_for' => ['What this rule is for', 'ما الغرض من هذه القاعدة'],

        // Rule sentence, assembled from whole sentences rather than words.
        'automation_rule_sentence' => [
            ':when, :then. At most :cap per run, waiting :cooldown between runs.',
            ':when، :then. بحدّ أقصى :cap في التشغيلة الواحدة، مع انتظار :cooldown بين التشغيلات.',
        ],
        'automation_when_low_stock' => [
            'When available stock falls to :threshold or fewer',
            'عندما ينخفض المخزون المتاح إلى :threshold أو أقل',
        ],
        'automation_when_out_of_stock' => [
            'When a product runs out of stock',
            'عندما ينفد مخزون المنتج',
        ],
        'automation_when_restocked_after_automation_hid_it' => [
            'When a product automation hid is back in stock',
            'عندما يعود إلى المخزون منتج أخفته الأتمتة',
        ],
        'automation_when_stale_stock' => [
            'When a product has not sold for :days days',
            'عندما لا يُباع المنتج مدة :days يوماً',
        ],
        'automation_then_hide_listing' => ['hide the listing', 'أخفِ العرض'],
        'automation_then_publish_listing' => ['publish the listing again', 'أعِد نشر العرض'],
        'automation_then_set_discount' => [
            'mark it down by :discount_value :discount_type, never below :min_price_after_discount',
            'خفّض سعره بمقدار :discount_value :discount_type، دون النزول تحت :min_price_after_discount',
        ],

        // Trigger and action names, as a person reads them.
        'automation_trigger_low_stock' => ['Stock running low', 'المخزون على وشك النفاد'],
        'automation_trigger_out_of_stock' => ['Out of stock', 'نفد المخزون'],
        'automation_trigger_restocked_after_automation_hid_it' => ['Back in stock', 'عاد إلى المخزون'],
        'automation_trigger_stale_stock' => ['Not selling', 'لا يُباع'],
        'automation_action_hide_listing' => ['Hide the listing', 'إخفاء العرض'],
        'automation_action_publish_listing' => ['Publish the listing', 'نشر العرض'],
        'automation_action_set_discount' => ['Set a discount', 'تطبيق خصم'],

        // Settings, named by the field they configure.
        'automation_field_threshold' => ['Stock threshold', 'حدّ المخزون'],
        'automation_field_days' => ['Days without a sale', 'أيام بلا بيع'],
        'automation_field_discount_type' => ['Discount type', 'نوع الخصم'],
        'automation_field_discount_value' => ['Discount amount', 'قيمة الخصم'],
        'automation_field_min_price_after_discount' => ['Never price below', 'لا تُنزل السعر تحت'],
        'automation_field_brand_ids' => ['Brands', 'العلامات التجارية'],
        'automation_field_category_ids' => ['Categories', 'الفئات'],
        'automation_field_product_ids' => ['Products', 'المنتجات'],
        'automation_option_percent' => ['Percent', 'نسبة مئوية'],
        'automation_option_flat' => ['Fixed amount', 'مبلغ ثابت'],
        'automation_discount_percent' => ['percent', 'بالمئة'],
        'automation_discount_flat' => ['off the price', 'من السعر'],

        // The safety class the server decides, never the screen.
        'automation_class_safe' => ['Runs automatically', 'يعمل تلقائياً'],
        'automation_class_restricted' => ['Cannot be automated', 'لا يمكن أتمتته'],
        'automation_class_restricted_reason' => [
            'Your role does not allow this action, so it cannot be run unattended on your behalf.',
            'دورك لا يسمح بهذا الإجراء، لذا لا يمكن تنفيذه نيابةً عنك دون إشراف.',
        ],
        'automation_class_not_revertible_reason' => [
            'This action cannot be put back, so it is not offered unattended.',
            'لا يمكن التراجع عن هذا الإجراء، لذلك لا يُتاح دون إشراف.',
        ],

        // Run outcomes. `matched` is never called `applied`.
        'automation_outcome_applied' => ['Applied', 'طُبِّق'],
        'automation_outcome_no_match' => ['Nothing matched', 'لا مطابقات'],
        'automation_outcome_capped' => ['Capped', 'تجاوز الحدّ'],
        'automation_outcome_failed' => ['Failed', 'فشل'],
        'automation_run_applied_one' => [
            'Changed 1 of :matched matched, skipping :skipped.',
            'غيّر 1 من :matched مطابقاً، وتخطّى :skipped.',
        ],
        'automation_run_applied_many' => [
            'Changed :count of :matched matched, skipping :skipped.',
            'غيّر :count من :matched مطابقاً، وتخطّى :skipped.',
        ],
        'automation_run_no_match_body' => [
            'The rule ran and found nothing to act on.',
            'عملت القاعدة ولم تجد ما تتصرف حياله.',
        ],
        'automation_run_capped_body' => [
            'This would have changed :matched products, more than the rule allows in one run, so nothing was changed.',
            'كان هذا سيغيّر :matched منتجاً، وهو أكثر مما تسمح به القاعدة في تشغيلة واحدة، فلم يُغيَّر شيء.',
        ],
        'automation_run_failed_body' => [
            'The run stopped before finishing.',
            'توقفت التشغيلة قبل أن تكتمل.',
        ],
        'automation_reason_skipped' => ['Skipped', 'مُتخطّى'],
        'ran_once_no_matches_yet' => ['Ran once · no matches yet', 'عملت مرة · لا مطابقات بعد'],
        'ran_n_times_no_matches_yet' => ['Ran :count times · no matches yet', 'عملت :count مرات · لا مطابقات بعد'],
        'n_seconds' => [':count seconds', ':count ثانية'],
        'n_selected' => [':count selected', ':count محدد'],
        'and_n_more' => ['and :count more', 'و:count أخرى'],
        'automation_scope_brands' => ['Brands: :names :more', 'العلامات: :names :more'],
        'automation_scope_categories' => ['Categories: :names :more', 'الفئات: :names :more'],
        'automation_scope_products' => ['Products: :names :more', 'المنتجات: :names :more'],

        // Screen copy.
        'rules_you_write_the_marketplace_runs_every_change_is_recorded_and_most_can_be_undone' => [
            'Rules you write, the marketplace runs. Every change is recorded, and most can be undone.',
            'قواعد تكتبها أنت وينفّذها السوق. كل تغيير مُسجَّل، ومعظمها قابل للتراجع.',
        ],
        'no_automations' => ['No automations', 'لا توجد أتمتة'],
        'create_rules_to_handle_repetitive_operational_tasks_automatically' => [
            'Create rules to handle repetitive operational tasks automatically.',
            'أنشئ قواعد لتتولّى المهام التشغيلية المتكررة تلقائياً.',
        ],
        'a_rule_watches_for_one_thing_and_does_one_thing_the_preview_shows_exactly_what_it_would_touch' => [
            'A rule watches for one thing and does one thing. The preview shows exactly what it would touch.',
            'القاعدة تراقب شيئاً واحداً وتفعل شيئاً واحداً. المعاينة تُظهر بالضبط ما ستمسّه.',
        ],
        'this_rule_was_not_saved' => ['This rule was not saved', 'لم تُحفظ هذه القاعدة'],
        'a_run_that_would_touch_more_than_the_cap_does_nothing_at_all_and_asks_for_a_person' => [
            'A run that would touch more than the cap does nothing at all, and asks for a person.',
            'التشغيلة التي ستمسّ أكثر من الحدّ لا تفعل شيئاً إطلاقاً، وتطلب تدخّل شخص.',
        ],
        'leave_empty_and_the_rule_applies_to_the_whole_catalogue' => [
            'Leave empty and the rule applies to the whole catalogue.',
            'اترك الحقل فارغاً وستُطبَّق القاعدة على كامل الكتالوج.',
        ],
        'choose_a_trigger_and_an_action_to_see_what_this_rule_would_do' => [
            'Choose a trigger and an action to see what this rule would do.',
            'اختر مُشغِّلاً وإجراءً لترى ما ستفعله هذه القاعدة.',
        ],
        'runs_the_rule_without_changing_anything_and_lists_what_it_would_touch' => [
            'Runs the rule without changing anything, and lists what it would touch.',
            'تُشغّل القاعدة دون تغيير أي شيء، وتسرد ما ستمسّه.',
        ],
        'delete_this_rule_the_record_of_what_it_did_stays' => [
            'Delete this rule? The record of what it did stays.',
            'هل تحذف هذه القاعدة؟ سجلّ ما فعلته يبقى.',
        ],
        'nothing_on_this_page_has_been_changed_this_is_what_the_rule_would_do_if_it_ran_now' => [
            'Nothing on this page has been changed. This is what the rule would do if it ran now.',
            'لم يُغيَّر أي شيء في هذه الصفحة. هذا ما ستفعله القاعدة لو عملت الآن.',
        ],
        'nothing_would_be_applied' => ['Nothing would be applied', 'لن يُطبَّق أي شيء'],
        'this_would_match_n_products_more_than_the_n_allowed_per_run' => [
            'This would match :matched products, more than the :cap allowed per run — nothing would be applied.',
            'سيطابق هذا :matched منتجاً، وهو أكثر من :cap المسموح بها في التشغيلة — لن يُطبَّق أي شيء.',
        ],
        'at_most_n_per_run' => ['At most :count per run', ':count كحدّ أقصى في التشغيلة'],
        'nothing_matches_right_now' => ['Nothing matches right now', 'لا مطابقات في هذه اللحظة'],
        'the_rule_is_written_correctly_it_simply_has_nothing_to_act_on_at_this_moment' => [
            'The rule is written correctly. It simply has nothing to act on at this moment.',
            'القاعدة مكتوبة بشكل صحيح، لكن لا يوجد ما تتصرف حياله في هذه اللحظة.',
        ],
        'every_run_of_every_rule_including_the_ones_that_matched_nothing' => [
            'Every run of every rule, including the ones that matched nothing.',
            'كل تشغيلة لكل قاعدة، بما فيها التي لم تطابق شيئاً.',
        ],
        'nothing_has_run_yet' => ['Nothing has run yet', 'لم يعمل شيء بعد'],
        'once_a_rule_is_active_every_run_it_makes_appears_here_with_what_it_touched' => [
            'Once a rule is active, every run it makes appears here with what it touched.',
            'بمجرد تفعيل قاعدة، تظهر هنا كل تشغيلة تقوم بها مع ما مسّته.',
        ],
        'no_runs_match_these_filters' => ['No runs match these filters', 'لا تشغيلات تطابق هذه المرشحات'],
        'this_run_touched_nothing' => ['This run touched nothing', 'لم تمسّ هذه التشغيلة شيئاً'],
        'the_rule_ran_and_found_nothing_to_act_on' => [
            'The rule ran and found nothing to act on.',
            'عملت القاعدة ولم تجد ما تتصرف حياله.',
        ],

        // ── wave 3 · opportunities (handoff 08 A5) ────────────────────────
        'opportunity_fast_sellers_at_stock_risk' => [
            'Fast-selling products at stock risk',
            'منتجات سريعة البيع مهدّدة بنفاد المخزون',
        ],
        'opportunity_high_traffic_low_conversion' => [
            'High traffic, low conversion',
            'زيارات كثيرة، مبيعات قليلة',
        ],
        'opportunity_priced_below_category_median' => [
            'Priced below the category median',
            'مُسعَّرة تحت وسيط فئتها',
        ],
        'opportunity_stock_risk_evidence' => [
            'From :days days of sales — less than :cover days of cover left at the current rate.',
            'من مبيعات :days يوماً — يتبقى أقل من :cover يوماً من التغطية بالمعدل الحالي.',
        ],
        'opportunity_conversion_evidence' => [
            'From :days days of product views against orders.',
            'من :days يوماً من مشاهدات المنتجات مقابل الطلبات.',
        ],
        'opportunity_price_evidence' => [
            'Compared against active listings in the same category.',
            'بالمقارنة مع العروض الفعّالة في الفئة نفسها.',
        ],
        'detected_from_the_last_n_days_of_your_own_shop_data' => [
            'Detected from the last :days days of your own shop data.',
            'مُكتشَفة من بيانات متجرك خلال آخر :days يوماً.',
        ],
        'no_opportunities_detected' => ['No opportunities detected', 'لا فرص مُكتشَفة'],
        'nothing_in_the_last_n_days_of_views_sales_and_prices_suggests_a_change_worth_making' => [
            'Nothing in the last :days days of views, sales and prices suggests a change worth making.',
            'لا شيء في آخر :days يوماً من المشاهدات والمبيعات والأسعار يشير إلى تغيير يستحق.',
        ],
        'review_stock' => ['Review stock', 'مراجعة المخزون'],
        'review_products' => ['Review products', 'مراجعة المنتجات'],
        'review_prices' => ['Review prices', 'مراجعة الأسعار'],
        'one_product' => ['1 product', 'منتج واحد'],
        'n_products' => [':count products', ':count منتجاً'],
        'nav_classic_dashboard' => ['Classic dashboard', 'اللوحة الكلاسيكية'],
    ];
}
