import {BASE, SHOTS, loginAdmin, watch, hasServerError} from '/home/user/Pharmacy/tests/browser/_env.mjs';
import {chromium} from 'playwright';
const section = process.argv[2];
const browser = await chromium.launch({executablePath: '/opt/pw-browsers/chromium'});
const page = await browser.newPage({viewport: {width: 1600, height: 1200}});
await page.emulateMedia({reducedMotion: 'reduce'});
const problems = watch(page);
await loginAdmin(page);
const res = await page.goto(BASE + '/admin/monitoring/' + section, {waitUntil: 'domcontentloaded'});
console.log(section, '->', res.status());
if (res.status() >= 400) problems.push(section + ' returned ' + res.status());
if (await hasServerError(page)) problems.push(section + ' rendered a server error');
await page.waitForTimeout(900);
await page.evaluate(() => document.querySelectorAll('.phpdebugbar,.modal,.modal-backdrop,.alert--container').forEach(n => n.remove()));
const placeholder = await page.locator('.k-empty').count();
const tables = await page.locator('.k-table').count();
const body = await page.locator('.mon-main').innerText();
console.log('tables:', tables, '| empty-states:', placeholder, '| body chars:', body.length);
await page.screenshot({path: SHOTS + '/mon-' + section + '.png', fullPage: true});
console.log(problems.length ? 'PROBLEMS:\n' + problems.join('\n') : 'ok');
await browser.close();
process.exit(problems.length ? 1 : 0);
