import {BASE, loginAdmin} from '/home/user/Pharmacy/tests/browser/_env.mjs';
import {chromium} from 'playwright';
const browser = await chromium.launch({executablePath: '/opt/pw-browsers/chromium'});
const page = await browser.newPage({viewport: {width: 1600, height: 1100}});
await page.emulateMedia({reducedMotion: 'reduce'});
await loginAdmin(page);
await page.goto(BASE + process.argv[2], {waitUntil: 'domcontentloaded'});
await page.waitForTimeout(600);
await page.evaluate(() => document.querySelectorAll('.phpdebugbar,.modal,.modal-backdrop,.alert--container').forEach((n) => n.remove()));
await page.locator('.mon-main').screenshot({path: process.argv[3]});
await browser.close();
