<?php

namespace App\Services\Telemetry;

use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

/**
 * Who a caller is when there is no cookie to ask.
 *
 * The api middleware group carries no cookie middleware, so every API and mobile-app request
 * arrives anonymous. Telemetry and analytics both had to answer "which visitor is this" for those
 * requests, and both had answered it the same wrong way — a salted hash of the address — in two
 * places, which is how the same mistake got fixed once and stayed broken elsewhere. One class now
 * holds the rule, and both read it.
 *
 * The rule, in descending order of what an identity is worth:
 *
 *  1. THE SIGNED-IN ACCOUNT. Exact, stable, survives a reinstall.
 *  2. AN INSTALLATION ID THE APP SENDS. Random, generated by the app at first launch, cleared when
 *     the user clears the app's data. Not a fingerprint: nothing about it is derived from the
 *     device, and the app can regenerate it whenever it likes.
 *  3. THE MASKED NETWORK ADDRESS. This identifies a NETWORK, not a person: every phone behind one
 *     carrier NAT is a single "visitor", and a household is one visitor for all its devices. A
 *     count built on it is a floor, so it is labelled and the reports say so. It also rotates
 *     daily — the address is salted with the date — so it can never become a permanent pseudonym.
 *
 * When none of the three is available there is no identity, and the caller records none. A shared
 * placeholder would merge every such request into one fictional visitor, which is worse than not
 * counting them: it is a number that looks like a measurement.
 */
class ClientIdentity
{
    /**
     * Headers a mobile app may send with a stable, random, per-install id it generated itself.
     *
     * Two names because two conventions are already in the wild; either is accepted, the first
     * present wins, and the value is hashed before it is stored.
     */
    public const CLIENT_ID_HEADERS = ['X-Client-Id', 'X-Device-Id'];

    /** Identity that names one account. */
    public const BASIS_USER = 'user';
    /** A first-party cookie the visitor can clear. */
    public const BASIS_COOKIE = 'cookie';
    /** An id the app generated for its own installation. */
    public const BASIS_CLIENT = 'client';
    /** A masked network address: one network, not one person. Approximate, and says so. */
    public const BASIS_NETWORK = 'network';

    /** Values that mean "I have no id" and would collapse an entire user base into one visitor. */
    private const PLACEHOLDERS = [
        'null', 'nil', 'none', 'unknown', 'undefined', 'n/a', '0',
        '00000000-0000-0000-0000-000000000000',
    ];

    /**
     * @return array{0: ?string, 1: ?string}  the identity and how it was reached; both null when
     *                                        the request offers neither an account, an id, nor an
     *                                        address
     */
    public function forApi(Request $request, ?string $userType, ?int $userId, bool $maskAddress = true): array
    {
        if ($userId !== null) {
            return ["api:{$userType}:{$userId}", self::BASIS_USER];
        }

        $client = $this->clientId($request);

        if ($client !== null) {
            return ['app:' . $this->salted($client), self::BASIS_CLIENT];
        }

        $network = $this->networkHash($request, $maskAddress);

        return $network === null ? [null, null] : ['net:' . $network, self::BASIS_NETWORK];
    }

    /**
     * The app's own installation id, if it sends one.
     *
     * Returned raw so the caller can decide what to do with it; it is never stored raw. The format
     * check is deliberately permissive about which id scheme an app chose and strict about length,
     * because a one-character "id" is not one.
     */
    public function clientId(Request $request): ?string
    {
        foreach (self::CLIENT_ID_HEADERS as $header) {
            $value = trim((string) $request->headers->get($header, ''));

            if (preg_match('/^[A-Za-z0-9._:-]{8,64}$/', $value) !== 1) {
                continue;
            }

            if (in_array(strtolower($value), self::PLACEHOLDERS, true)) {
                continue;
            }

            return $value;
        }

        return null;
    }

    /**
     * An address, masked to its network and salted with today's date.
     *
     * Never enough to recover where anyone was, and never the same value tomorrow — which is the
     * only reason it is allowed to stand in for an identity at all.
     */
    public function networkHash(Request $request, bool $mask = true): ?string
    {
        $address = (string) $request->ip();

        if ($address === '') {
            return null;
        }

        if ($mask) {
            $address = filter_var($address, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)
                ? implode(':', array_slice(explode(':', $address), 0, 4)) . '::'
                : preg_replace('/\.\d+$/', '.0', $address);
        }

        return $this->salted($address, rotateDaily: true);
    }

    private function salted(string $value, bool $rotateDaily = false): string
    {
        $salt = config('app.key') . ($rotateDaily ? '|' . Carbon::now()->toDateString() : '');

        return substr(hash('sha256', $value . '|' . $salt), 0, 40);
    }
}
