{{-- Get the app. The QR is generated by the same service the campaign builder
     uses, over the same deep link, so the code on a poster and the code on this
     page open the same thing. --}}

@php
    $appStyle = $s['style'] ?? 'split';
    $androidUrl = $appStores['android'] ?? null;
    $iosUrl = $appStores['ios'] ?? null;
    $qrSvg = ($s['qr'] ?? true)
        ? app(\App\Services\Analytics\Support\QrCode::class)->svg(url('/'), 132)
        : null;
@endphp
    <div class="ml-getapp ml-getapp--{{ $appStyle }} ml-reveal">
        <div class="ml-getapp__copy">
            @if (!empty($s['eyebrow']))<span class="ml-eyebrow">{{ $s['eyebrow'] }}</span>@endif
            <h3>{{ $s['title'] ?: translate('get_the_app') }}</h3>
            @if (!empty($s['subtitle']))<p>{{ $s['subtitle'] }}</p>@endif
            <div class="ml-getapp__badges">
                @if ($androidUrl)
                    <a class="ml-btn ml-btn-gold" href="{{ $androidUrl }}" rel="noopener">{{ translate('google_play') }}</a>
                @endif
                @if ($iosUrl)
                    <a class="ml-btn ml-btn-light" href="{{ $iosUrl }}" rel="noopener">{{ translate('app_store') }}</a>
                @endif
            </div>
        </div>
        @if ($qrSvg)
            <div class="ml-getapp__qr">{!! $qrSvg !!}</div>
        @elseif (!empty($s['image']))
            <div class="ml-getapp__art"><img src="{{ $s['image'] }}" alt="" loading="lazy"></div>
        @endif
    </div>
